# Generated by Django 5.0.6 on 2024-07-15 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTest',
        ),
    ]
